# Generated by Django 3.2.2 on 2021-05-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.TextField(default='(303) xxx-xxxx', max_length=50),
            preserve_default=False,
        ),
    ]
